kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cifs-flexvol-pvc001
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: cifs-flexvol-pv001
