apiVersion: v1
kind: PersistentVolume
metadata:
  name: cifs-flexvol-pv002
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "fstab/cifs"
    secretRef:
      name: cifs-secret-01
    options:
      source: "//34.248.205.56/privateshare"
      mountOptions: "vers=3.0,dir_mode=0777,file_mode=0777"
