kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cifs-flexvol-pvc002
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: cifs-flexvol-pv002
